apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wptest-web
        env:
        - name: WORDPRESS_DB_NAME
          value: wp
        - name: WORDPRESS_DB_HOST
          value: 127.0.0.1
        - name: WORDPRESS_DB_USER
          value: wordpress
        - name: WORDPRESS_DB_PASSWORD
          value: w0rdpr3ss
        image: docker.io/library/wordpress:latest
        ports:
        - containerPort: 80
          hostPort: 8080
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: true
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          seLinuxOptions: {}
        workingDir: /var/www/html
      - name: wptest-db
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: myrootpass
        - name: MYSQL_USER
          value: wordpress
        - name: MYSQL_PASSWORD
          value: w0rdpr3ss
        - name: MYSQL_DATABASE
          value: wp
        image: docker.io/library/mariadb:latest
        resources: {}
        securityContext:
          allowPrivilegeEscalation: true
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          seLinuxOptions: {}
        workingDir: /
